server:
  port: 7900
  
spring:
  application:
    name: provider-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatisdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: tarena
            
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka

mybatis:
  mapUnderscoreToCamelCase: true
  typeAliasesPackage: cn.tedu.ssm.pojo
  mapperLocations: classpath:mappers/*.xml
  
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level: 
    cn.tedu.ssm.mapper: debug
